#!/bin/sh
# Run each test and compare
# against known good output

if [ ! -f ../myComp ]
then echo "Need to build ../myComp first!"; exit 1
fi

for i in input*
do if [ ! -f "out.$i" -a ! -f "err.$i" ]
  then echo "Can't run test on $i, no output file!"

  else if [ -f "out.$i" ]
  then
    echo -n "$i"
    ../myComp "$i"
    cc -o out out.s ../lib/printint.c
    ./out > trial."$i"
    diff -b -B "out.$i" "trial.$i"
    if [ "$?" -eq "1" ]
    then
      echo ": failed"
      diff -c "out.$i" "trial.$i"
      echo
      exit 1
    else echo ": OK"
    fi

  else if [ -f "err.$i" ]
  then
    echo -n "$i"
    ../myComp "$i" 2> "trial.$i"
    diff -b -B "err.$i" "trial.$i"
    if [ "$?" -eq "1" ]
    then
      echo ": failed"
      diff -c "err.$i" "trial.$i"
      echo
      exit 1
    else echo ": OK"
    fi
  fi
  fi
  fi
  rm -f out out.s "trial.$i"
done
